import './App.css';
import Navbar from 'react-bootstrap/Navbar'
import { Media, Row, Col, Button, Image } from 'react-bootstrap';

function App() {
  return (
    <div>
      <Navbar bg="dark" variant="dark">
        <Navbar.Brand href="#home">
          <img
            src="/tracex_logo.png"
            width="30"
            height="30"
            className="d-inline-block align-top"
            alt="TraceX App Logo"
          />{' '}
          TraceX
        </Navbar.Brand>
      </Navbar>
      <div style={{ marginTop: '40px' }}>
        <Row>
          <Col xl={{ span: 6, offset: 3 }} style={{ border: '1px solid lightgrey', borderRadius: '5px', boxShadow: 'darkgrey' }}>
            <Image style={{margin:'10px 0px 10px 0px', width:'100%', height:'400px' }} src="/contacttracing.png" fluid></Image>
            <Media style={{ margin: '25px' }}>
              <img
                width={80}
                height={80}
                className="mr-3"
                src="/tracex_logo.png"
                alt="Generic placeholder"
              />
              <Media.Body>
                <h1>TraceX</h1>
                <h3 style={{ color: 'grey' }}> Privacy-Protected Contact Tracing Platform</h3>
                <h5 style={{ color: 'black' }}>Developers : Chi Hoang, Juhi Nayak, Rashmi Sarode, Sneha Patil</h5>
                <p>
                  TraceX is a privacy-protected contact tracing application that can be utilized at any part of the world.
                  In the first version of the application we have targeted the USA. The app is built with Android version 7 and above.
                </p>
                <p>
                  TraceX helps to fight against the current pandemic situation by helping people to be aware of the circumstances.
                  It is advisable to know about the people who are affected by any harmful contagious disease and take respective measures.
                </p>
                <p>
                  TraceX does not intend to share any private information of the user. The app uses Bluetooth technology to share the advertising
                  ID of the devices. In order to adhere to the privacy-policy, we use the BLE tokens generated by the mobile device.
                  These tokens can’t be considered as private information because it keeps changing at certain periods of time. Hence,
                  protects users to be tracked at any time. In case the user has been infected, we also take user’s consent by asking whether
                  they would like to share their device data with TraceX to notify other people or not. TraceX then notifies other people who have
                  been in their contact for more than 2 minutes within 6 feet of distance in the past 14 days.
                </p>
                <p>
                  TraceX also provides information from reliable sources through interactive graphs and numbers.
                  The user can also maintain their health history by checking in to the app.
                </p>
                <p>
                  The app is developed by a team of 4 students pursuing masters in Software Engineering at San Jose State University.
                  The app is reliable and excellent in terms of performance and privacy. The outcome of TraceX is a privacy protected contact
                  tracing platform helping people to increase awareness and slowing down the spread of any contagious disease.
                </p>
                <p>
                  Follow below methods before dowloading the app on your android devices.
                  The opt-in process depends on the version of Android running on the user's device::
                </p>
                <ul>
                  <li>On devices running Android 8.0 (API level 26) and higher,
                    users must navigate to the Install unknown apps system settings screen to enable app installations from a particular source.
                    <ol>
                      <li>Open “Settings“</li>
                      <li>Search “Install unknown apps“ in the search settings</li>
                      <li>Choose the application (chrome, firefox etc) you are installing the APK file from</li>
                      <li>Toggle the “Allow from this source” option to “On“.</li>
                    </ol>
                  </li>
                  <li>On devices running Android 7.1.1 (API level 25) and lower, users must either enable the Unknown sources system setting or
                    allow a single installation of an unknown app.
                    <ol>
                      <li>Open “Settings“</li>
                      <li>Select "Security"</li>
                      <li>Enable the "Unknown sources" setting</li>
                    </ol>
                  </li>
                </ul>
                <p>
                  Download the app using following button:
                </p>
                <Button variant="success" size="lg" href="/TraceX.apk" block>Download</Button>
              </Media.Body>
            </Media>
          </Col>
        </Row>
      </div>
    </div>
  );
}

export default App;
